backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "properties"
    label: "Properties"
    folder: "src/data/properties"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Details (e.g., 3 Beds | 2 Baths)", name: "details", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Latitude", name: "lat", widget: "number", value_type: "float"}
      - {label: "Longitude", name: "lon", widget: "number", value_type: "float"}
      - {label: "Body", name: "body", widget: "markdown", required: false}

