backend:
  name: auth0
  domain: AUTH0_DOMAIN
  client_id: AUTH0_CLIENT_ID
  use_local_storage: true

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "properties"
    label: "Properties"
    folder: "src/data/properties"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Details", name: "details", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Latitude", name: "lat", widget: "number", hint: "Decimal value" }
      - { label: "Longitude", name: "lon", widget: "number", hint: "Decimal value" }
