backend:
  name: git-gateway
  branch: main # or 'master' — use your actual default branch name

site_url: https://tazaproperties.com

media_folder: "static/uploads" # where uploaded images will be stored in your repo
public_folder: "/uploads"      # how those images appear on your site

collections:
  - name: "properties"          # name used internally by CMS
    label: "Properties"         # name shown in the CMS UI
    folder: "content/properties" # folder in your repo to store entries
    create: true
    slug: "{{slug}}"             # file name pattern
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
