backend:
  name: auth0
  domain: VITE_APP_AUTH0_DOMAIN # These will be replaced by Netlify's build process
  client_id: VITE_APP_AUTH0_CLIENT_ID
  auth_scope: openid profile email

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "properties"
    label: "Properties"
    folder: "src/data/properties"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Details", name: "details", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Latitude", name: "lat", widget: "number", value_type: "float"}
      - {label: "Longitude", name: "lon", widget: "number", value_type: "float"}

